function func_scalability_yy(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 03-Sep-2021 20:52:59

% Create figure
figure1 = figure;

axes1 = axes('Parent',figure);
hold(axes1,'on');

yyaxis(axes1,'left');
% Create plot
plot(X1,Y1,'MarkerSize',15,'Marker','pentagram','LineWidth',2);

ylim(axes1,[0 1]);
xlim(axes1,[142 800]);
% Create ylabel
ylabel({'Efficiency'});

yyaxis(axes1,'right');

plot(X1,Y2,'MarkerSize',15,'Marker','diamond','LineWidth',2);

% Create ylabel
ylabel({'degrees of freedom (in millions)'});

% Create xlabel
xlabel({'# of processes'});

box(axes1,'on');

% Set the remaining axes properties
set(axes1,'FontSize',16, 'XTick',[142,300,514,784]);
