function nlbargraph(xvector1, ymatrix1, Y1)
%CREATEFIGURE(xvector1, ymatrix1, Y1)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 18-Oct-2021 14:36:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1,'BarLayout','stacked');
set(bar1(2),'DisplayName','Setup');
set(bar1(1),'DisplayName','Solve');

% Create plot
plot(xvector1,Y1,'DisplayName','Linear Reduction in Time','LineWidth',2,...
    'Color',[0 0 0]);

% Create ylabel
ylabel({'Time to Solution (s)'});

% Create xlabel
xlabel({'# processors'});

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',16,'XTick',[80 160 240 320 400 600]);
% Create legend
legend(axes1,'show');

