function func_scalability_L(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 03-Sep-2021 20:52:59

% Create figure
figure1 = figure;

axes1 = axes('Parent',figure);
hold(axes1,'on');

yyaxis(axes1,'left');
% Create plot
plot(X1,Y1,'MarkerSize',15,'Marker','pentagram','LineWidth',2);

% Create ylabel
ylabel({'Time (s)'});

yyaxis(axes1,'right');

plot(X1,Y2,'MarkerSize',15,'Marker','diamond','LineWidth',2);

% Create ylabel
ylabel({'degrees of freedom (in millions)'});

% Create xlabel
xlabel({'Number of Processes'});
xticks([40, 80, 160, 240, 400]);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16);
